export const LOGIN_ACTIONS = {
  LOGIN_USER_GOOGLE_REQUEST: "LOGIN_USER_GOOGLE_REQUEST",
  LOGIN_USER_GOOGLE_SUCCESS: "LOGIN_USER_GOOGLE_SUCCESS",
  LOGIN_USER_GOOGLE_FAILURE: "LOGIN_USER_GOOGLE_FAILURE",
  SET_AUTHENTICATED_USER: "SET_AUTHENTICATED_USER"
};

export const LOGOUT_ACTIONS = {
  LOGOUT_USER_GOOGLE_REQUEST: "LOGOUT_USER_GOOGLE_REQUEST",
  LOGOUT_USER_GOOGLE_SUCCESS: "LOGOUT_USER_GOOGLE_SUCCESS",
  LOGOUT_USER_GOOGLE_FAILURE: "LOGOUT_USER_GOOGLE_FAILURE"
};
